## Intro to Dataframes

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.DataFrame([[1,2,3],[4,5,6],[7,8,9],[10,11,12]], columns=["A", "B", "C"], index=["x","y","z",'zz'])

In [4]:
df.head()

     A   B   C
x    1   2   3
y    4   5   6
z    7   8   9
zz  10  11  12

In [5]:
df.tail(2)

     A   B   C
z    7   8   9
zz  10  11  12

In [6]:
df.columns

Index(['A', 'B', 'C'], dtype='object')

In [7]:
df.index.tolist()

['x', 'y', 'z', 'zz']

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, x to zz
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   A       4 non-null      int64
 1   B       4 non-null      int64
 2   C       4 non-null      int64
dtypes: int64(3)
memory usage: 128.0+ bytes

In [9]:
df.describe()

               A          B          C
count   4.000000   4.000000   4.000000
mean    5.500000   6.500000   7.500000
std     3.872983   3.872983   3.872983
min     1.000000   2.000000   3.000000
25%     3.250000   4.250000   5.250000
50%     5.500000   6.500000   7.500000
75%     7.750000   8.750000   9.750000
max    10.000000  11.000000  12.000000

In [10]:
df.nunique()

A    4
B    4
C    4
dtype: int64

In [11]:
df['A'].unique()

array([ 1,  4,  7, 10])

In [ ]:
df.shape

In [ ]:
df.size

In [ ]:
df

## Loading in Dataframes from Files

In [ ]:
coffee = pd.read_csv('../DataSets/coffee.csv')

In [ ]:
results = pd.read_parquet('../DataSets/results.parquet')
bios = pd.read_csv('../DataSets/bios.csv')

In [ ]:
## To read an excel spreadsheet
olympics_data = pd.read_excel('../DataSets/olympics-data.xlsx', sheet_name="results")

## Accessing Data with Pandas

In [ ]:
print(coffee)

In [ ]:
display(coffee)

In [ ]:
coffee.head()

In [ ]:
coffee.tail(10)

In [ ]:
coffee.sample(5) # Pass in random_state to make deterministic

In [ ]:
# loc
# coffee.loc[Rows, Columns]

coffee.loc[0]

In [ ]:
coffee.loc[[0,1,5]]

In [ ]:
coffee.loc[5:9, ["Day", "Units Sold"]]

#### iloc

In [ ]:
coffee.iloc[:, [0,2]]

#### Other Stuff

In [ ]:
coffee.index = coffee["Day"]

In [ ]:
coffee.loc["Monday":"Wednesday"]

In [ ]:
coffee = pd.read_csv('./warmup-data/coffee.csv')

#### Setting Values

In [ ]:
coffee.loc[1:3, "Units Sold"] = 10

#### Optimized way to get single values (.at & .iat)

In [ ]:
coffee.at[0,"Units Sold"]

In [ ]:
coffee.iat[3,1]

#### Getting Columns

In [ ]:
coffee.Day

In [ ]:
coffee["Day"]

#### Sort Values

In [ ]:
coffee.sort_values(["Units Sold"], ascending=False)

In [ ]:
coffee.sort_values(["Units Sold", "Coffee Type"], ascending=[0,1])

#### Iterate over dataframe with for loop

In [ ]:
for index, row in coffee.iterrows():
    print(index)
    print(row)
    print("Coffee Type of Row:", row["Coffee Type"])

## Filtering Data

In [ ]:
bios.head()

In [ ]:
bios.loc[bios["height_cm"] > 215]

In [ ]:
bios.loc[bios["height_cm"] > 215, ["name", "height_cm"]]

#### Short-hand syntax (without .loc)

In [ ]:
bios[bios['height_cm'] > 215][["name","height_cm"]]

#### Multiple filter conditions

In [ ]:
bios[(bios['height_cm'] > 215) & (bios['born_country']=='USA')]

#### Filter by string conditions

In [ ]:
bios[bios['name'].str.contains("keith", case=False)]

In [ ]:
# Regex syntax
bios[bios['name'].str.contains('keith|patrick', case=False)]

In [ ]:
## isin method & startswith
bios[bios['born_country'].isin(["USA", "FRA", "GBR"]) & (bios['name'].str.startswith("Keith"))]

#### Query functions

In [ ]:
bios.query('born_country == "USA" and born_city == "Seattle"')

## Adding / Removing Columns

In [ ]:
coffee.head()

In [ ]:
coffee['price'] = 4.99

In [ ]:
coffee['new_price'] = np.where(coffee['Coffee Type']=='Espresso', 3.99, 5.99)

In [ ]:
coffee

In [ ]:
coffee.drop(columns=['price'], inplace=True)

# the below would also have worked
# coffee = coffee.drop(columns=['price'])

In [ ]:
coffee = coffee[['Day', 'Coffee Type', 'Units Sold', 'new_price']]

In [ ]:
coffee['revenue'] = coffee['Units Sold'] * coffee['new_price']

In [ ]:
coffee

In [ ]:
coffee.rename(columns={'new_price': 'price'}, inplace=True)

In [ ]:
bios_new = bios.copy()

In [ ]:
bios_new['first_name'] = bios_new['name'].str.split(' ').str[0]

In [ ]:
bios_new.query('first_name == "Keith"')

In [ ]:
bios_new['born_datetime'] = pd.to_datetime(bios_new['born_date'])

In [ ]:
bios_new['born_year'] = bios_new['born_datetime'].dt.year

In [ ]:
bios_new[['name','born_year']]

In [ ]:
bios_new.to_csv('./data/bios_new.csv', index=False)

In [ ]:
bios['height_category'] = bios['height_cm'].apply(lambda x: 'Short' if x < 165 else ('Average' if x < 185 else 'Tall'))

In [ ]:
def categorize_athlete(row):
    if row['height_cm'] < 175 and row['weight_kg'] < 70:
        return 'Lightweight'
    elif row['height_cm'] < 185 or row['weight_kg'] <= 80:
        return 'Middleweight'
    
    else:
        return 'Heavyweight'
    
bios['Category'] = bios.apply(categorize_athlete, axis=1)

In [ ]:
bios.head()

## Merging & Concatenating Data

In [ ]:
nocs = pd.read_csv('./data/noc_regions.csv')

In [ ]:
bios_new = pd.merge(bios, nocs, left_on='born_country', right_on='NOC', how='left')

In [ ]:
bios_new.rename(columns={'region': 'born_country_full'}, inplace=True)

In [ ]:
usa = bios[bios['born_country']=='USA'].copy()
gbr = bios[bios['born_country']=='GBR'].copy()

In [ ]:
new_df = pd.concat([usa,gbr])

In [ ]:
new_df.tail()

In [ ]:
combined_df = pd.merge(results, bios, on='athlete_id', how='left')

In [ ]:
combined_df.head()

## Handling Null Values

In [ ]:
coffee.loc[[2,3], 'Units Sold'] = np.nan

In [ ]:
# Make sure to set this to your Units Sold column if you want these changes to stick
coffee['Units Sold'].fillna(coffee['Units Sold'].mean())

In [ ]:
# coffee['Units Sold'] = coffee['Units Sold'].interpolate()
coffee['Units Sold'].interpolate()

In [ ]:
coffee.dropna(subset=['Units Sold']) # Use inplace=True if you want to update the coffee df

In [ ]:
coffee[coffee['Units Sold'].notna()]

In [ ]:
coffee

## Aggregating Data

In [ ]:
bios.head()

In [ ]:
bios['born_city'].value_counts()

In [ ]:
bios[bios['born_country']=='USA']['born_region'].value_counts().head(10)

In [ ]:
bios[bios['born_country']=='USA']['born_region'].value_counts().tail(25)

#### Groupby function in Pandas

In [ ]:
coffee.groupby(['Coffee Type'])['Units Sold'].sum()

In [ ]:
coffee.groupby(['Coffee Type'])['Units Sold'].mean()

In [ ]:
coffee.groupby(['Coffee Type', 'Day']).agg({'Units Sold': 'sum', 'price': 'mean'})

#### Pivot Tables

In [ ]:
pivot = coffee.pivot(columns='Coffee Type', index='Day', values='revenue')

In [ ]:
pivot.sum()

In [ ]:
pivot.sum(axis=1)

#### Using datetime with Groupby

In [ ]:
bios['born_date'] = pd.to_datetime(bios['born_date'])
bios['month_born'] = bios['born_date'].dt.month
bios['year_born'] = bios['born_date'].dt.year
bios.groupby([bios['year_born'],bios['month_born']])['name'].count().reset_index().sort_values('name', ascending=False)

## Advanced Functionality

In [ ]:
# shift() rank() cumsum() rolling()

In [ ]:
latte = coffee[coffee['Coffee Type']=="Latte"].copy()
latte['3day'] = latte['Units Sold'].rolling(3).sum()

In [ ]:
latte